import type { Metadata } from 'next';
import Link from 'next/link';
import { Inter, Noto_Sans_KR } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });
const noto = Noto_Sans_KR({
  subsets: ['latin'],
  variable: '--noto-font',
});

export const metadata: Metadata = {
  title: 'Create My Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className} ${noto.className}`}>
        <header className='bg-cyan-300'>Header...</header>
        {children}
        <Link href='/csr'>CSR</Link>
        <Link href='/about'>ABOUT</Link>
        <footer className='bg-blue-300'>Footer...</footer>
      </body>
    </html>
  );
}
